Reworking of includes and layouts episodes as per #208
carpentries-incubator/jekyll-pages-novice pull request #242
Opened 2021-05-11 18:41 UTC by anenadic

Reworking of includes and layouts episodes:

- code reuse examples now use navigational links and footer
- layouts inheritance is shown on the example of home layout inheriting from default layout and adding a banner image

Example code repository with for reference: https://github.com/anenadic/group-website

2021-05-12 16:06 UTC, tobyhodges requested changes
This is a fantastic effort, @anenadic! A few suggestions, mostly minor typos and language polishing. We are almost good to go with this one 🎉

2021-05-12 16:06 UTC, tobyhodges commented on _episodes/includes.md
> +we could add the same code above to each Markdown file in our repository.
```suggestion
we could add the same code immediately after the YAML header of each Markdown file in our repository.
```

2021-05-12 16:06 UTC, tobyhodges commented on _episodes/includes.md
> +But if we wanted to adjust the - adjust the navigation link target, add a new navigation link, remove a link, etc. -
```suggestion
But if we wanted to adjust the menu - adjust the navigation link target, add a new navigation link, remove a link, etc. -
```

2021-05-12 16:06 UTC, tobyhodges commented on _episodes/includes.md
> +we would need to make the same adjustment on every page.
```suggestion
we would need to make the same adjustment on every page.
This is both time-consuming and error-prone: 
it would be easy to accidentally mistype a link or forget to update one of the files.
```

2021-05-12 16:06 UTC, tobyhodges commented on _episodes/includes.md
> +5. Now insert the following `_include` directive at the beginning of `index.md`:
```suggestion
5. Now insert the following `include` directive at the beginning of `index.md`:
```

2021-05-12 16:06 UTC, tobyhodges commented on _episodes/includes.md
> +To demonstrate this, we will save the HTML snippet for creating navigation links into
```suggestion
To demonstrate this, we will save an HTML snippet for creating navigation links into
```

2021-05-12 16:06 UTC, tobyhodges commented on _episodes/includes.md
> +some magic that Jekyll provides: `include` tags.
```suggestion
some magic that Jekyll provides: `include` tags.

```

I think a paragraph break helps readability here.

2021-05-12 16:06 UTC, tobyhodges commented on _episodes/includes.md
> +    # {{ site.title }}
```suggestion
    # Building Websites in GitHub
```

`{{ site.title }}` was removed in #241

2021-05-12 16:06 UTC, tobyhodges commented on _episodes/includes.md
> +## Reusing Footer
```suggestion
## Reusable Footer 
```

2021-05-12 16:06 UTC, tobyhodges commented on _episodes/includes.md
> +> re-use in multiple places throughout your site as a footer.
```suggestion
> reuse in multiple places throughout your site as a footer.
```

to keep consistent with the changes made elsewhere in this PR.

2021-05-12 16:06 UTC, tobyhodges commented on _episodes/includes.md
> +> Convert the above Markdown snippet into HTML and save it into `_includes/footer.html` file,
```suggestion
> Convert the above Markdown snippet into HTML and save it into a `_includes/footer.html` file,
```

2021-05-12 16:06 UTC, tobyhodges commented on _episodes/includes.md
> +> then use the `include` directive to re-insert it
```
> then use the `include` directive to re-insert it
```

If we are using "reuse" now instead of "re-use," do you think this should be "reinsert?"

2021-05-12 16:06 UTC, tobyhodges commented on _episodes/includes.md
> +> why we meed the file to be in HTML rather than Markdown shortly.
```suggestion
> why we need the file to be in HTML rather than Markdown shortly.
```

2021-05-12 16:06 UTC, tobyhodges commented on _episodes/layouts.md
> +we will start with a layout file that only includes this file:
```suggestion
we will start with a layout file that only includes this these links:
```

2021-05-13 12:11 UTC, anenadic commented on _episodes/includes.md
> +> then use the `include` directive to re-insert it
Sounds good - I have probably introduced a few more inconsistencies along the way. Also how we refer to "our repository" vs "your repository" interchangeably. The whole lesson would benefit from a language polish - will add a separate issue.

2021-05-13 12:25 UTC, anenadic commented
Thanks for the review @tobyhodges ❤️ . I have committed all your changes (let me know if I've missed anything). I suggest I go now and resolve conflicts and merge the latest changes from gh-pages branch and then ask you to have another quick look and merge. Then the whole team can have look at the narrative and flow and fix any issues. Does that sound like a plan?

2021-05-13 13:56 UTC, anenadic commented
Latest changes: 
- Merged from gh-pages.
- Added more screenshots to showcase adding of a header and a footer. 
- Restyled the footer section not to be in the form of an exercise but rather the main text (as there is quite a lot going on that may require the instructor to show). 
- Reverted the footer section name to 'Reusing Footer' instead of 'Reusable Footer' to be consistent with other headings in the episode. 
- Resolved all conflicts.
Review request pls @tobyhodges.

2021-05-14 08:21 UTC, tobyhodges approved these changes
Awesome, thank you @anenadic !

2021-05-14 08:21 UTC, merged