Filling in some gaps in the introduction
carpentries-incubator/jekyll-pages-novice pull request #38
Opened 2020-09-11 11:35 UTC by tobyhodges

2020-09-18 21:25 UTC, sstevens2 approved these changes
This looks like a great addition to me.  I left one comment but it might be due to my local render because I don't see anything wrong.

2020-09-18 21:25 UTC, sstevens2 commented on _episodes/01-introduction.md
> +_Figure 1.1: Page Generation Alternatives. This figure was originally published in [JavaScript for Data Science][js4ds], and is reproduced here with permission from the original author._
Maybe just something with the local rendering but it isn't rendering the `js4ds` link right.  I can't see anything wrong with it though.

2020-09-28 19:22 UTC, unode requested changes
Minor typos, otherwise :+1:

2020-09-28 19:22 UTC, unode commented on _episodes/01-introduction.md
> +**CSS** - an ordered set of styling instructions telling the browser how to the content should be organised and formatted -
```suggestion
**CSS** - an ordered set of styling instructions telling the browser how the content should be organised and formatted -
```

2020-09-28 19:22 UTC, unode commented on _episodes/01-introduction.md
> +**CSS** - an ordered set of styling instructions telling the browser how to the content should be organised and formatted -
```suggestion
**CSS** - an ordered set of styling instructions telling the browser how the content should be organised and formatted -
```

2020-09-28 19:22 UTC, unode commented on _episodes/01-introduction.md
> +and when they visit,
```suggestion
display on a website is the same regardless of who visits your site,
when they visit,
```

2020-09-28 19:22 UTC, unode commented on _episodes/01-introduction.md
> +and leaves feeling happy and fulfilled.
```suggestion
the aim of the page is to always deliver the same information.
The visitor arrives,
(hopefully) finds and reads what they need
and leaves feeling happy and fulfilled.
```

2020-09-29 06:44 UTC, merged